version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn optimizer_service.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./optimizer_service:/app/optimizer_service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - LLM_PROVIDER=vllm
      - VLLM_HOST=vllm
      - VLLM_PORT=8000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=rpc://redis:6379/0
  worker:
    build: .
    command: celery -A optimizer_service.worker.celery_app worker --loglevel=info
    volumes:
      - ./optimizer_service:/app/optimizer_service
    depends_on:
      - redis
    environment:
      - LLM_PROVIDER=vllm
      - VLLM_HOST=vllm
      - VLLM_PORT=8000
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=rpc://redis:6379/0
  vllm:
    image: vllm/vllm-openai:latest
    command:
      - --host
      - "0.0.0.0"
      - --model
      - "defog/sqlcoder-7b-2"
      - --dtype
      - auto
      - --max-model-len
      - "8192"
      - --gpu-memory-utilization
      - "0.90"
    volumes:
      - ./vllm_data:/root/.cache/huggingface
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  vllm_data: